# Generated by Django 2.1.7 on 2019-05-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgpost',
            name='rating',
        ),
    ]
