# Generated by Django 2.1.7 on 2019-05-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190514_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpost',
            name='pub_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
