# Generated by Django 2.1.7 on 2019-05-17 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190514_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 17, 18, 48, 32, 691096, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='imgpost',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
