# Generated by Django 2.1.7 on 2019-05-21 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190520_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 21, 9, 52, 45, 352345, tzinfo=utc)),
        ),
    ]
