# Generated by Django 2.1.7 on 2019-05-21 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190521_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 21, 10, 26, 30, 999206, tzinfo=utc)),
        ),
    ]
