# Generated by Django 2.1.7 on 2019-05-21 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20190521_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgpost',
            name='site_users',
        ),
        migrations.AddField(
            model_name='imgpost',
            name='author',
            field=models.ForeignKey(default=324, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imgpost',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
