# Generated by Django 2.1.7 on 2019-05-22 17:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190521_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpost',
            name='author',
            field=models.ForeignKey(default=django.contrib.auth.models.AbstractUser.get_full_name, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
