# Generated by Django 2.1.7 on 2019-05-22 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190522_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
        migrations.AlterField(
            model_name='imgpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
