# Generated by Django 2.1.7 on 2019-05-23 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190522_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpost',
            name='author',
            field=models.ForeignKey(default='b', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
