# Generated by Django 2.1.7 on 2019-05-23 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190523_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgpost',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='imgpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
