# Generated by Django 2.1.7 on 2019-05-23 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190523_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgPostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='imgpost',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='imgposttag',
            name='img_tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='main.ImgPost'),
        ),
    ]
