# Generated by Django 2.1.7 on 2019-06-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190528_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpost',
            name='photo',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to=''),
        ),
    ]
