# Generated by Django 2.1.7 on 2019-07-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190610_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
